basic:
  token: "eyJ0eXAiOiJKc2.....HrwyN0"
  tenant: "NZJftK0pCDI4Ng=="
  student_id: "392522123456731891"
  start_image: "C:\\path\\to\\your\\start_image.jpg" #希望锻炼开始的照片是哪一张，填入路径即可。照片大小最好在200KB以内（约200x600）。注意，使用Windows默认的反斜杠需要进行转义。
  finish_image: "C:\\path\\to\\your\\finish_image.jpg" #希望锻炼结束的照片是哪一张，填入路径即可。照片大小最好在200KB以内（约200x600）。注意，使用Windows默认的反斜杠需要进行转义。
  date: "2025-04-01" #锻炼进行的日期
  start_time: "18:00:00" #锻炼开始的时间
  finish_time: "18:08:00" #锻炼结束的时间
  seconds: "480" #所经过的秒数。最好不要与锻炼的开始时间和结束时间相冲突。
  distance: "1.24" #锻炼的距离，单位为公里
  calorie: "77" #消耗的卡路里
  speed: "6'52''" #配速，如果不清楚格式，不建议修改
  display_time: "00:08:00" #显示界面上的时间

advanced:
  baseUrl: "tyxsjpt.seu.edu.cn"
  miniappversion: "minappv3.0.1"
  UA: "Mozilla/5.0 (Linux; Android 7.1.2; V2284A Build/N2G47H; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160253 MMWEBSDK/20240301 MMWEBID/4107 MicroMessenger/8.0.48.2580(0x28003036) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android"
  rule_id: "402186368309502988"
  plan_id: "403640124545491473"
  route_name: "桃园田径场"
  route_rule: "九龙湖校区"